language: node_js
node_js:
  - 14

cache:
  yarn: true
  directories:
    - node_modules

install:
  - bash ./.travis/install.sh

script:
  - yarn run contracts
  - bash ./.travis/test-truffle.sh
  #- yarn run test
  #- yarn run build
