language: node_js
node_js:
  - 14

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run contracts
  - cd contracts && npx truffle develop & && npx truffle test --network=develop
  - yarn run test
  - yarn run build
