version: "3.7"
services:
  ganache:
    image: trufflesuite/ganache-cli
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic=${MNEMONIC}
      - --chainId=5779
      - --networkId=5779
      - --gasPrice=5e9
    volumes:
      - .ganache:/ganache_data
    ports:
      - "7545:8545"
