version: "3.7"
services:
  ganache:
    image: trufflesuite/ganache-cli
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic=${MNEMONIC}
      - --chainId=5779
      - --networkId=5779
      - --gasPrice=5e9
    volumes:
      - .ganache:/ganache_data
    ports:
      - "7545:8545"
  ipfs:
    image: ipfs/go-ipfs:latest
    command: "daemon --init --enable-pubsub-experiment"
    ports:
      - "4041-4049:4001"
      - "4041-4049:4001/udp"
      - "5051-5059:5001"
      - "127.0.0.1:8081-8089:8080"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000


